### ISSUE TITLE
Compilation fails when using plain hdf5 headers and -DO2SCL_PLAIN_HDF5_HEADER does not help

### ISSUE THREAD

**Issue by badshah400** [awsteiner/o2scl#19]
This used to work with o2scl version v0.926, but with v0.927 using `CXXFLAGS+=" -DO2SCL_PLAIN_HDF5_HEADER"` does not help compilations when hdf5 uses the plain header:

```
[   24s] /usr/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\"  -DO2SCL_EIGEN   -DO2SCL_COND_FLAG -DO2SCL_READLINE   -DO2SCL_LINUX     -I     -DO2SCL_PLAIN_HDF5_HEADER -c -o cli.lo cli.cpp
[   24s] libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\" -DO2SCL_EIGEN -DO2SCL_COND_FLAG -DO2SCL_READLINE -DO2SCL_LINUX -I -DO2SCL_PLAIN_HDF5_HEADER -c cli.cpp  -fPIC -DPIC -o .libs/cli.o
[   24s] In file included from cli.cpp:26:
[   24s] ../../include/o2scl/hdf_file.h:35:10: fatal error: hdf5/serial/hdf5.h: No such file or directory
[   24s]    35 | #include <hdf5/serial/hdf5.h>
[   24s]       |          ^~~~~~~~~~~~~~~~~~~~
[   24s] compilation terminated.
[   24s] make[4]: *** [Makefile:1051: cli.lo] Error 1
[   24s] make[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/o2scl-0.927/src/base'
[   24s] make[4]: *** Waiting for unfinished jobs....
[   25s] make[4]: Entering directory '/home/abuild/rpmbuild/BUILD/o2scl-0.927/src/base'
[   25s] /usr/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\"  -DO2SCL_EIGEN   -DO2SCL_COND_FLAG -DO2SCL_READLINE   -DO2SCL_LINUX     -I     -DO2SCL_PLAIN_HDF5_HEADER -c -o lib_settings.lo lib_settings.cpp
[   25s] libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\" -DO2SCL_EIGEN -DO2SCL_COND_FLAG -DO2SCL_READLINE -DO2SCL_LINUX -I -DO2SCL_PLAIN_HDF5_HEADER -c lib_settings.cpp  -fPIC -DPIC -o .libs/lib_settings.o
[   25s] lib_settings.cpp:38:10: fatal error: hdf5/serial/hdf5.h: No such file or directory
[   25s]    38 | #include <hdf5/serial/hdf5.h>
[   25s]       |          ^~~~~~~~~~~~~~~~~~~~
[   25s] compilation terminated.
[   25s] make[4]: *** [Makefile:1051: lib_settings.lo] Error 1

```

Specific library versions:

* hdf5 1.12.2 (On openSUSE, the hdf headers are at `/usr/include/hdf5.h`, `/usr/include/hdf5_hl.h`)
* GCC 12.1

Full build log attached for reference
[_log.zip](https://github.com/awsteiner/o2scl/files/9387669/_log.zip)

**Comment by awsteiner** [comment]
I'm checking my dockerfile for openSUSE tumbleweed right now but does using CXXFLAGS=/usr/include help? PLAIN_HDF5_HEADER means that hdf_file.h just uses "#include <hdf5.h>" so as long as you have the right CXX flags it should work...

**Comment by badshah400** [comment]
I think there is something going on with the conditionals in that header file (and in `./src/base/lib_settings.cpp`). If I remove all the `#if` stuff as follows (just for a demo), the build looks up the `hdf5.h` header just fine (without any additional CXXFLAGS).

```diff
Index: o2scl-0.927/src/hdf/hdf_file.h
===================================================================
--- o2scl-0.927.orig/src/hdf/hdf_file.h
+++ o2scl-0.927/src/hdf/hdf_file.h
@@ -28,15 +28,7 @@
 */
 #include <limits>
 
-#ifdef O2SCL_PLAIN_HDF5_HEADER
 #include <hdf5.h>
-#else
-#ifdef O2SCL_LINUX
-#include <hdf5/serial/hdf5.h>
-#else
-#include <hdf5.h>
-#endif
-#endif
 
 #include <boost/numeric/ublas/vector.hpp>
 #include <boost/numeric/ublas/matrix.hpp>
```

**Comment by badshah400** [comment]
It is the final ` -I` at the end of the CXXFLAGS that causes the issue, probably causes it to treat the `-DO2SCL_PLAIN_HDF5_HEADER` as the directory for `-I`. This only happens when building without python support, so using `--enable-python` and `CXXFLAGS+=" -DO2SCL_PLAIN_HDF5_HEADER"` works perfectly.

The flags when python is enabled is now:

```
[   22s] /usr/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\"  -DO2SCL_EIGEN   -DO2SCL_COND_FLAG -DO2SCL_READLINE   -DO2SCL_LINUX   -DO2SCL_PYTHON  -I/usr/include/python3.10     -DO2SCL_PLAIN_HDF5_HEADER -c -o funct.lo funct.cpp
```

while without python enabled they are as follows:

```
[   15s] /usr/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include/ -DO2SCL_DATA_DIR=\"/usr/share/o2scl/\" -DO2SCL_DOC_DIR=\"/usr/share/doc/o2scl/\"  -DO2SCL_EIGEN   -DO2SCL_COND_FLAG -DO2SCL_READLINE   -DO2SCL_LINUX     -I     -DO2SCL_PLAIN_HDF5_HEADER -c -o lib_settings.lo lib_settings.cpp
```

with flags coming after the `-I` being specified by me.

**Comment by awsteiner** [comment]
oh i see thank you. i'll check src/base/Makefile.am because it is supposed to make sure there aren't any empty -I flags like that.

**Comment by badshah400** [comment]
This fixes it for me (regardless of building with or without python)

```
Index: o2scl-0.927/src/base/Makefile.am
===================================================================
--- o2scl-0.927.orig/src/base/Makefile.am
+++ o2scl-0.927/src/base/Makefile.am
@@ -107,7 +107,7 @@ O2SCL_MPFR_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -132,7 +132,7 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(ADDINC) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_FFTW_MVAR) $(O2SCL_LINUX_MVAR) \
 	$(O2SCL_MPFR_MVAR) $(O2SCL_POLYLOGARITHM_MVAR) \
-	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) -I$(PYTHON_INCLUDE_DIR) \
+	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) \
 	$(O2SCL_PUGIXML_MVAR) 
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ \
@@ -142,7 +142,7 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(ADDINC) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_FFTW_MVAR) $(O2SCL_LINUX_MVAR) \
 	$(O2SCL_MPFR_MVAR) $(O2SCL_POLYLOGARITHM_MVAR) \
-	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) -I$(PYTHON_INCLUDE_DIR) \
+	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) \
 	$(O2SCL_PUGIXML_MVAR) 
 endif
```

**Comment by badshah400** [comment]
Sorry, please ignore previous comment, perhaps spoke too soon.

**Comment by badshah400** [comment]
It is that, just in more places. Finally fixed with the following:

```diff
Index: o2scl-0.927/src/base/Makefile.am
===================================================================
--- o2scl-0.927.orig/src/base/Makefile.am
+++ o2scl-0.927/src/base/Makefile.am
@@ -107,7 +107,7 @@ O2SCL_MPFR_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -132,7 +132,7 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(ADDINC) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_FFTW_MVAR) $(O2SCL_LINUX_MVAR) \
 	$(O2SCL_MPFR_MVAR) $(O2SCL_POLYLOGARITHM_MVAR) \
-	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) -I$(PYTHON_INCLUDE_DIR) \
+	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) \
 	$(O2SCL_PUGIXML_MVAR) 
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ \
@@ -142,7 +142,7 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(ADDINC) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_FFTW_MVAR) $(O2SCL_LINUX_MVAR) \
 	$(O2SCL_MPFR_MVAR) $(O2SCL_POLYLOGARITHM_MVAR) \
-	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) -I$(PYTHON_INCLUDE_DIR) \
+	$(O2SCL_PYTHON_MVAR) $(O2SCL_CUBATURE_MVAR) \
 	$(O2SCL_PUGIXML_MVAR) 
 endif
 
Index: o2scl-0.927/bin/Makefile.am
===================================================================
--- o2scl-0.927.orig/bin/Makefile.am
+++ o2scl-0.927/bin/Makefile.am
@@ -53,7 +53,7 @@ O2SCL_PUGIXML_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -64,13 +64,13 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(O2SCL_PUGIXML_MVAR) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR) $(O2SCL_FFTW_MVAR) \
-	$(O2SCL_PYTHON_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	$(O2SCL_PYTHON_MVAR)
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ -DO2SCL_DATA_DIR=\"${datadir}/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
 	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(O2SCL_PUGIXML_MVAR) \
 	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR) $(O2SCL_FFTW_MVAR) \
-	$(O2SCL_PYTHON_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	$(O2SCL_PYTHON_MVAR)
 endif
 
 # ------------------------------------------------------------      
Index: o2scl-0.927/src/fit/Makefile.am
===================================================================
--- o2scl-0.927.orig/src/fit/Makefile.am
+++ o2scl-0.927/src/fit/Makefile.am
@@ -33,7 +33,7 @@ O2SCL_ARMA_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -46,8 +46,7 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ -I
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ -DO2SCL_DATA_DIR=\"${datadir}/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
-	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR) \
-	-I$(PYTHON_INCLUDE_DIR)
+	$(O2SCL_GSL2_MVAR) -DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR)
 endif
 
 # ------------------------------------------------------------
Index: o2scl-0.927/src/root/Makefile.am
===================================================================
--- o2scl-0.927.orig/src/root/Makefile.am
+++ o2scl-0.927/src/root/Makefile.am
@@ -40,7 +40,7 @@ O2SCL_ARMA_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -49,11 +49,11 @@ if O2SCL_SNAP
 AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	-DO2SCL_DATA_DIR=\"/snap/o2scl/current/share/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
-	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR)
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ -DO2SCL_DATA_DIR=\"${datadir}/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
-	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR)
 endif
 
 # ------------------------------------------------------------
Index: o2scl-0.927/src/eos/Makefile.am
===================================================================
--- o2scl-0.927.orig/src/eos/Makefile.am
+++ o2scl-0.927/src/eos/Makefile.am
@@ -71,7 +71,7 @@ O2SCL_OSX_MVAR =
 endif
 
 if O2SCL_PYTHON
-O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON
+O2SCL_PYTHON_MVAR = -DO2SCL_PYTHON -I$(PYTHON_INCLUDE_DIR)
 else 
 O2SCL_PYTHON_MVAR = 
 endif
@@ -81,12 +81,12 @@ AM_CPPFLAGS = -I@top_srcdir@/include/ \
 	-DO2SCL_DATA_DIR=\"/snap/o2scl/current/share/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
 	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR) \
-	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR)
 else
 AM_CPPFLAGS = -I@top_srcdir@/include/ -DO2SCL_DATA_DIR=\"${datadir}/o2scl/\" \
 	$(O2SCL_OPENMP_MVAR) $(O2SCL_EIGEN_MVAR) $(O2SCL_ARMA_MVAR) \
 	-DO2SCL_COND_FLAG $(O2SCL_PYTHON_MVAR) \
-	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR) -I$(PYTHON_INCLUDE_DIR)
+	$(O2SCL_OSX_MVAR) $(O2SCL_LINUX_MVAR)
 endif
 
 # ------------------------------------------------------------
```

**Comment by awsteiner** [comment]
Ok yes thank you very much. I made a new branch, v0.927.fix, and made these changes in b369f73

**Comment by badshah400** [comment]
Thanks for the quick responses on your part.

Unrelated to this (I can report in separate issues if you prefer), I ended up requiring a couple more patches to get o2scl v0.927 building. These are as follows:

* Error due to missing namespace specification for `isfinite` here: https://github.com/awsteiner/o2scl/blob/3efff42a65099004d8ab6ce8d7866ec1156ba94e/src/base/convert_units.h#L1557-L1558
```diff
Index: o2scl-0.927/src/base/convert_units.h
===================================================================
--- o2scl-0.927.orig/src/base/convert_units.h
+++ o2scl-0.927/src/base/convert_units.h
@@ -1558,8 +1558,8 @@ namespace o2scl {
         // powers of K
         set_vars(1.0,1.0,1.0,2.0,1.0,1.0,1.0,vars);
         kb_power=calc.eval(&vars)/calc2.eval(&vars)/before*after;
-        if (!isfinite(calc.eval(&vars)) ||
-            !isfinite(calc2.eval(&vars))) {
+        if (!boost::math::isfinite(calc.eval(&vars)) ||
+            !boost::math::isfinite(calc2.eval(&vars))) {
           std::cout << "Not finite result in convert."
                     << std::endl;
           O2SCL_ERR("Not finite.",o2scl::exc_efailed);
```
* Linking to quadmath explicitly (otherwise I see errors complaining about missing references to `floorq`, `isinfq`, and others), which I fixed thus (probably can be better)
```diff
Index: o2scl-0.927/configure.ac
===================================================================
--- o2scl-0.927.orig/configure.ac
+++ o2scl-0.927/configure.ac
@@ -66,6 +66,7 @@ AC_SUBST(OLIB_LT_VERSION)
 # ------------------------------------------------------------------
 
 AC_CHECK_LIB([m],[cos])
+AC_CHECK_LIB([quadmath],[floorq])
 
 # ------------------------------------------------------------------
 # Check for BLAS
```

Happy to report that with these patches, o2scl builds on openSUSE Tumbleweed now.

**Comment by awsteiner** [comment]
you're welcome and thank you. the isfinite() call is fixed for 0.927 on ed2b33fb and for 0.928a1 on 366e222b. I'm not sure why argument-dependent-lookup doesn't work here, but this is a good fix. i've also had problems on other systems with boost::multiprecision requiring quadmath even when the associated types are never explicitly used, apparently because quadmath is used internally. this feels to me like a boost bug, but I don't have a good testcase for it. i'd like not to have to put quadmatch in configure.ac because of limitations on OSX, but this may need to change in the future.

**Comment by awsteiner** [comment]
Closing for now let me know if anything else arises.

**Comment by badshah400** [comment]
Thanks for checking in the fixes.

I think we should be OK carrying the quadmath patch for o2scl packages on openSUSE. I could also send you a patch for the `configure.ac` file with conditionals that only look for quadmath on Linux so that it avoids issues with OSX. Please let me know if you would prefer that.
